<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MainTest</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>b8dd347e-f62f-4481-8710-55bb6d51379b</testSuiteGuid>
   <testCaseLink>
      <guid>01999a12-2111-4821-8cc0-285a934eb8bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SearchProduct</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0be6dfa5-ef04-43be-a06e-4ef296e62cd2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da091512-49db-40e5-8d50-7ddc0028d91f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29c91349-5d0e-4747-aa7a-290083c093d3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e4c4002-a1cb-47d8-b233-5cf4e7e69c6c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Register</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c89c8f0-3ef7-4465-a5e5-5cb06c95f865</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ef9643d8-b802-4356-8813-80e99b74b896</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee3d1eb2-c74d-4db4-ae0b-b8fde90b8c76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33f78e28-ae94-4fc8-89c1-17691a25fa3f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8692cb0c-df38-495a-ba61-f02dad505172</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f16bef72-d781-4f17-80a4-3297eafc680f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>827336ec-c1f3-41c9-b6de-526f655ffc3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d1b08a1b-16e9-462f-9beb-bccb669dfee2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
